### ISSUE TITLE
Верстка 2-го элемента

### ISSUE THREAD

**Issue by Dimitry-prog** [Lokrand/lubimovka-project#1]
- [x] блок с видео
- [x] блок с текстом
- [x] блок с фотографиями (при клике на фото открывается поп-ап)

**Comment by Dimitry-prog** [comment]
Готов блок с видео

**Comment by Lokrand** [comment]
Круто!

**Comment by Dimitry-prog** [comment]
Эту ишье передвигаю на ревью
